name: Notificar cambio de estado (Kanban cl치sico)

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informaci칩n
        run: echo "La issue ${{ github.event.issue.number }} cambi칩 de etiqueta."

      - name: Comentar en la issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            游댒 La tarea *#${{ github.event.issue.number }}* cambi칩 su estado a *${{ github.event.label.name }}*.